In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
matrix=np.arange(32,72).reshape(10,4)
print("matrix:\n",matrix)
print("SHAPE:",matrix.shape)
print("TYPE:",type(matrix))

matrix:
 [[32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]
 [64 65 66 67]
 [68 69 70 71]]
SHAPE: (10, 4)
TYPE: <class 'numpy.ndarray'>


In [ ]:
array1=np.arange(15,45)
print(array1)
print("size:",len(array1))
array1[8]=980
print(array1)
print("reverse:",array1[::-1])
print(array1.reshape(6,5))
array1[:6]*=-1
print(array1)
print(np.concatenate(-1*array1[:7],array1[7:]))


[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44]
size: 30
[ 15  16  17  18  19  20  21  22 980  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39  40  41  42  43  44]
reverse: [ 44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29  28  27
  26  25  24 980  22  21  20  19  18  17  16  15]
[[ 15  16  17  18  19]
 [ 20  21  22 980  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [ 40  41  42  43  44]]
[-15 -16 -17 -18 -19 -20  21  22 980  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39  40  41  42  43  44]
[ 15  16  17  18  19  20 -21  22 980  24  25  26  27  28  29  30  31  32
  33  34  35  36  37  38  39  40  41  42  43  44]


In [ ]:
#Write a numpy program to create a 8 x 8 matrix and fill it with a checkerboard pattern
# [[1 1 0 0 0 0 1 1]
# [0 0 1 1 1 1 0 0]
# ..
# …
# [0 0 1 1 1 1 0 0]]

matrix=np.ones((8,8),dtype=int)
matrix[::2,2:-2]=0
matrix[1::2,:2]=0
matrix[1::2,-2:]=0
print(matrix)


[[1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 0 0 0 0 1 1]
 [0 0 1 1 1 1 0 0]]


In [ ]:
a=np.array([1,2,3,4,5,6])
b=np.array([5,6,7,8])
print(np.isin(b,a))


[ True  True False False]


In [ ]:
a=np.array([1,2,3,4,5,6])
b=np.array([5,6,7,8])
print(np.intersect1d(a,b))
print(np.union1d(a,b))

[5 6]
[1 2 3 4 5 6 7 8]


In [ ]:
#  6) Write a numpy program to save a given array to textfile and load it.Also
# convert a given array to csv file and load it.

array1=np.array([[1,2],[3,4]],dtype=int)
print(array1)
np.savetxt("elements.csv",array1)
loaded=np.loadtxt("elements.csv",dtype=int)
print(loaded)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


/tmp/ipython-input-74-2511876458.py:7: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  loaded=np.loadtxt("elements.csv",dtype=int)


In [ ]:
array1=np.array([[2,3],[4,7]])
print("array 1\n",array1)
print(list(array1))
print(array1.tolist())
print(array1.reshape(-1))

array 1
 [[2 3]
 [4 7]]
[array([2, 3]), array([4, 7])]
[[2, 3], [4, 7]]
[2 3 4 7]


In [ ]:
array1=np.array([[7,8,9],[4,5,6],[1,2,3]])
print(array1)
access1stcolumn=array1[:,0]
print("first column = \n",access1stcolumn)

[[7 8 9]
 [4 5 6]
 [1 2 3]]
first column = 
 [7 4 1]


In [ ]:
# 9)Write a numpy program to compute
#    a) multiplication of two given matrices.
#    b) addition of two matrices

array1=np.array([[7,8,9],[4,5,6],[1,2,3]])
array2=np.array([[17,18,19],[14,15,16],[11,12,13]])
mul=np.dot(array1,array2)
add=array1+array2
print("mul=\n",mul)
print("add=\n",add)
multi=np.multiply(array1,array2)
print("mul(like add)=\n",multi)
multi=np.matmul(array1,array2)
print("matmul(like dot)=\n",multi)


mul=
 [[330 354 378]
 [204 219 234]
 [ 78  84  90]]
add=
 [[24 26 28]
 [18 20 22]
 [12 14 16]]
mul(like add)=
 [[119 144 171]
 [ 56  75  96]
 [ 11  24  39]]
matmul(like dot)=
 [[330 354 378]
 [204 219 234]
 [ 78  84  90]]


In [ ]:
# 10)Write a numpy program to eigenvalues and eigenvectors of a given matrix
array1=np.array([[2,2,1],[1,3,1],[1,2,2]])
w , v= np.linalg.eig(array1)
print("eigen value:\n", w)
print("eigen vector:\n", v)

eigen value:
 [5. 1. 1.]
eigen vector:
 [[-0.57735027 -0.90453403  0.82529864]
 [-0.57735027  0.30151134 -0.52125218]
 [-0.57735027  0.30151134  0.21720572]]


In [ ]:
# 11)Write a program to find transpose, determinant and inverse of a matrix.
array1=np.array([[2,2,1],[1,3,1],[1,2,2]])

print("\nmatrix:\n", array1)

print("\ntranspose of matrix:\n", np.transpose(array1))

determinant_result=np.linalg.det(array1)
print("\ndetereminent of matrix:\n", round(determinant_result, 6))

print("\ninverse of matrix:\n", np.linalg.inv(array1))


matrix:
 [[2 2 1]
 [1 3 1]
 [1 2 2]]

transpose of matrix:
 [[2 1 1]
 [2 3 2]
 [1 1 2]]

detereminent of matrix:
 5.0

inverse of matrix:
 [[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]
